### ISSUE TITLE
Problems in build 3.1.16 using Postgres 11 using the postgres Docker Debian

### ISSUE THREAD

**Issue by cesarjorgemartinez** [ossc-db/pg_bulkload#97] opened 2021-05-06 16:27 UTC
Hi,

I having trouble trying to build pg_bulkload (https://github.com/ossc-db/pg_bulkload/tree/VERSION3_1_16) in postgres Docker Debian (https://hub.docker.com/_/postgres).

Then I write:
apt-get install build-essential postgresql-server-dev-11 postgresql-contrib-11 libpam-dev libssl-dev libreadline-dev libselinux-dev libedit-dev

But show the following errors that I don't know how need to fix or find other libraries:

```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer pg_bulkload.o recovery.o pgut/pgut.o pgut/pgut-fe.o pgut/pgut-list.o  -L/usr/lib/x86_64-linux-gnu -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-6.0/lib  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed -Wl,--build-id  -L/usr/lib/x86_64-linux-gnu -lpq -lpgcommon -lpgport -lpthread -lselinux -lpam -lssl -lcrypto -lgssapi_krb5 -lz -ledit -lrt -lcrypt -ldl -lm -o pg_bulkload
/usr/bin/ld: cannot find -lpgcommon
/usr/bin/ld: cannot find -lpgport
collect2: error: ld returned 1 exit status
/usr/lib/postgresql/11/lib/pgxs/src/makefiles/pgxs.mk:430: recipe for target 'pg_bulkload' failed
```

How find pgcommon or pgport to install?

Regards,
Cesar Jorge

**Comment by mikecaat** [comment] 2021-05-07 00:53
Hi,

Thanks for reporting!
I think the packages are already installed because postgres-server-dev-11 has them.

```
> apt-file search pgcommon
postgresql-server-dev-11: /usr/lib/postgresql/11/lib/libpgcommon.a

> apt-file search pgport
postgresql-server-dev-11: /usr/lib/postgresql/11/lib/libpgport.a
```

I think the cause is that these libraries don't exist in the search path. The build logs said that the directory for library files is `/usr/lib/x86_64-linux-gnu`, but the installed directory is `/usr/lib/postgresql/11/lib`.

Now, the [PR](https://github.com/ossc-db/pg_bulkload/pull/98) to fix this problem is reviewed and it will be merged. 

If you want to the specific tag(VERSION3_1_16), this [issue](https://github.com/zalando/spilo/issues/228) and [PR](https://github.com/zalando/spilo/pull/229/files) can help you although these were made in another project. To make the symlinks is an easy workaround.

Regards,
Masahiro Ikeda

**Comment by cesarjorgemartinez** [comment] 2021-05-07 07:52
Thank you so much,

Yes, I need exact version because I involved in a migration task, and I need exact versions of plugins.
I will to apply this workaround and comment.

**Comment by cesarjorgemartinez** [comment] 2021-05-07 07:55
Why don't you not use the official docker postgres as?:

```
FROM postgres:11.11
```

**Comment by mikecaat** [comment] 2021-05-07 08:44
> Yes, I need exact version because I involved in a migration task, and I need exact versions of plugins.

OK. I understood.

> I will to apply this workaround and comment.

Thanks! I hope it will work.

> Why don't you not use the official docker postgres as?:
> ```
> 
> FROM postgres:11.11
> 
> ```

No reason, but I think yours is better.

**Comment by mikecaat** [comment] 2021-05-27 01:28
Close this issue because the PR is merged.

**Closed by mikecaat** 2021-05-27 01:28 UTC
