### ISSUE TITLE
Regression test: WARNING:  Ignore 4 bytes at the end of file

### ISSUE THREAD

**Issue by japinli** [ossc-db/pg_bulkload#76] opened 2019-04-26 08:46 UTC
Hi,

Recently, I run pg_bulkload-3.1.15 with PostgreSQL-11.2 on SunOS 5.11, when I run regression test and there are two tests are failed:

```
$ make installcheck
make[1]: Entering directory '/home/japin/pg_bulkload-3.1.15/bin'
/home/japin/pg11.2/lib/postgresql/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/home/japin/pg11.2/bin'    --dbname=contrib_regression  --encoding=UTF8 init load_bin load_csv load_remote load_function load_encoding load_check load_filter load_parallel write_bin
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test init                         ... FAILED
test load_bin                     ... FAILED
test load_csv                     ... ok
test load_remote                  ... ok
test load_function                ... ok
test load_encoding                ... ok
test load_check                   ... ok
test load_filter                  ... ok
test load_parallel                ... ok
test write_bin                    ... ok

=======================
 2 of 10 tests failed.
=======================

The differences that caused some tests to fail can be viewed in the
file "/home/japin/pg_bulkload-3.1.15/bin/regression.diffs".  A copy of the test summary that you see
above is saved in the file "/home/japin/pg_bulkload-3.1.15/bin/regression.out".

make[1]: *** [/home/japin/pg11.2/lib/postgresql/pgxs/src/makefiles/pgxs.mk:408: installcheck] Error 1
make[1]: Leaving directory '/home/japin/pg_bulkload-3.1.15/bin'
make[1]: Entering directory '/home/japin/pg_bulkload-3.1.15/lib'
make[1]: Nothing to be done for 'installcheck'.
make[1]: Leaving directory '/home/japin/pg_bulkload-3.1.15/lib'
make[1]: Entering directory '/home/japin/pg_bulkload-3.1.15/util'
make[1]: Nothing to be done for 'installcheck'.
make[1]: Leaving directory '/home/japin/pg_bulkload-3.1.15/util'
make: *** [Makefile:33: installcheck] Error 2
```

You can see more detail about why `test init` case failed in #75. What I am concern is why the `test load_bin` case failed. I run this regression test on both Ubuntu 18.04.2 LTS and SunOS 5.11, and only SunOS failed, here is content of the regression.diff on SunOS:

```
$ cat bin/regression.diffs 
*** /home/japin/pg_bulkload-3.1.15/bin/expected/init_1.out      Fri Jan 18 02:52:40 2019
--- /home/japin/pg_bulkload-3.1.15/bin/results/init.out Fri Apr 26 08:33:53 2019
***************
*** 1,6 ****
--- 1,7 ----
  SET client_min_messages = warning;
  \set ECHO none
  CREATE LANGUAGE 'plpgsql';
+ ERROR:  language "plpgsql" already exists
  RESET client_min_messages;
  CREATE TABLE customer (
      c_id            int4 NOT NULL,

======================================================================

*** /home/japin/pg_bulkload-3.1.15/bin/expected/load_bin.out    Fri Jan 18 02:52:40 2019
--- /home/japin/pg_bulkload-3.1.15/bin/results/load_bin.out     Fri Apr 26 08:33:56 2019
***************
*** 860,865 ****
--- 860,866 ----
  CPU <TIME>s/<TIME>u sec elapsed <TIME> sec
  \! echo -n "" | pg_bulkload -d contrib_regression data/bin5.ctl -l results/bin10.log -o PRESERVE_BLANKS=YES -o "COL=10"
  NOTICE: BULK LOAD START
+ WARNING:  Ignore 4 bytes at the end of file
  NOTICE: BULK LOAD END
        0 Rows skipped.
        0 Rows successfully loaded.
***************
*** 923,928 ****
--- 924,930 ----
  CPU <TIME>s/<TIME>u sec elapsed <TIME> sec
  \! echo -n "" | pg_bulkload -d contrib_regression data/bin5.ctl -l results/bin11.log -o PRESERVE_BLANKS=NO -o "COL=10"
  NOTICE: BULK LOAD START
+ WARNING:  Ignore 4 bytes at the end of file
  NOTICE: BULK LOAD END
        0 Rows skipped.
        0 Rows successfully loaded.

======================================================================
```

Also, I checked the md5 of `bin/data/bin5.ctl`, and they are identical. I don't know why SunOS report `WARNING:  Ignore 4 bytes at the end of file`.

**Comment by MoonInsung** [comment] 2021-06-24 08:58
Dear @japinli

In the case of the pg_bulkload latest version,
the regression test passed due to checking of PostgreSQL 9.6 or higher all versions.
So let's close this issue.
If the problem occurs again in the pg_bulkload latest version,
please reopen it.

Best regards.
Moon.

**Closed by MoonInsung** 2021-06-24 08:58 UTC
