### ISSUE TITLE
Regression test failed

### ISSUE THREAD

**Issue by japinli** [ossc-db/pg_bulkload#75] opened 2019-04-26 08:10 UTC
Hi,

When I use pg_bulkload-3.1.15 with PostgreSQL-11.2, everything works will except regression test.
Here is my regression test results:

```
*** /home/japin/oracle/pg_bulkload-3_1_15/bin/expected/init_1.out       2019-01-18 10:52:40.000000000 +0800
--- /home/japin/oracle/pg_bulkload-3_1_15/bin/results/init.out  2019-04-26 15:59:50.689948353 +0800
***************
*** 1,6 ****
--- 1,7 ----
  SET client_min_messages = warning;
  \set ECHO none
  CREATE LANGUAGE 'plpgsql';
+ ERROR:  language "plpgsql" already exists
  RESET client_min_messages;
  CREATE TABLE customer (
      c_id            int4 NOT NULL,

======================================================================
```

According to the results, we do not need `CREATE LANGUAGE 'plpgsql';` in PostgreSQL-11.2.

**Comment by japinli** [comment] 2019-04-26 09:08
Maybe we can use `REGRESS_OPTS = --load-language=plpgsql` in `bin/Makefile`. To do that we should remove `CREATE LANGUAGE plpgsql;` which is in `bin/sql/init.sql`, and modify the expected result out.

**Comment by MoonInsung** [comment] 2021-06-24 08:57
Dear @japinli 

In the case of the pg_bulkload latest version, 
the regression test passed due to checking of PostgreSQL 9.6 or higher all versions.
So let's close this issue.
If the problem occurs again in the pg_bulkload latest version, 
please reopen it.

Best regards.
Moon.

**Closed by MoonInsung** 2021-06-24 08:57 UTC
