### ISSUE TITLE
Binary conversion does not work properly when reading text data from a user-defined function.

### ISSUE THREAD

**Issue by MoonInsung** [ossc-db/pg_bulkload#93] opened 2021-04-13 07:42 UTC
In the case of pg_bulkload version 3.1.17, the following problem occurred.

```
**_Binary conversion does not work properly when reading text data from a user-defined function.
This is a problem when reading text data of a user-define function while using the "-o TYPE=FUNCTION" option of pg_bulkload._**
```

For PostgreSQL versions 13 and later, there was a modification to the executor related to the function, which requires improvement in pg_bulkload.

An example of a simple problem reproduction is shown below.
```
1. Create functions
CREATE FUNCTION exc_char_fnc() RETURNS SETOF RECORD AS $$
    VALUES (11, 12, 13, 14, 15, 1.1, 1.2)
    ;
$$ LANGUAGE SQL;

CREATE FUNCTION inc_char_fnc() RETURNS SETOF RECORD AS $$
    VALUES (11, 12, 13, 14, 15, 1.1, 1.2,'test1')
    ;
$$ LANGUAGE SQL;
```

```
2. Create control files
exc_char.ctl
WRITER = BINARY
PARSE_ERRORS = -1
OUT_COL = SMALLINT
OUT_COL = INTEGER
OUT_COL = BIGINT
OUT_COL = UNSIGNED SMALLINT
OUT_COL = UNSIGNED INTEGER
OUT_COL = FLOAT
OUT_COL = DOUBLE
MULTI_PROCESS = YES


inc_char.ctl
WRITER = BINARY
PARSE_ERRORS = -1
OUT_COL = SMALLINT
OUT_COL = INTEGER
OUT_COL = BIGINT
OUT_COL = UNSIGNED SMALLINT
OUT_COL = UNSIGNED INTEGER
OUT_COL = FLOAT
OUT_COL = DOUBLE
OUT_COL = CHAR (10)
MULTI_PROCESS = YES
```

```
3. Run to pg_bulkload
bin/pg_bulkload -d postgres exc_char.ctl -i "exc_char_fnc()" -o TYPE=FUNCTION -O exc_char_test.out
bin/pg_bulkload -d postgres inc_char.ctl -i "inc_char_fnc()" -o TYPE=FUNCTION -O inc_char_test.out
```

In this case, when loading data from a text column, the following error message occurs:
```
ERROR:  return type mismatch in function declared to return record
DETAIL:  Final statement returns text instead of cstring at column.
```

I don't think it's a common feature, but it's an inconvenient problem, so I think we need to fix it in the next release.

**Comment by mikecaat** [comment] 2021-04-21 07:39
Hi, 

Thanks for reporting. I can reproduce the above issue.

If my understanding is right, this issue is occurred by this postgresql's [patch](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=913bbd88dc6b859c70ebb48107b38d693c4c6673).

This patch adds to check if the system can cast for each column. From before the patch is merged, the system couldn't cast the assignment cast from the text to cstring type which pg_bulkload expects, so the error occurs.

The patch also modified the documents. It said the following and there is an example to define custom type for a function
> We must ensure each expression's type can be cast to that of the corresponding column of the composite type.

So, I tried to specify the type and check if it works with Postgresql 13.2 and pg_bulkload 3.1.17.

```
1. Create a type and a function

psql=# CREATE TYPE test_type AS (id1 smallint, id2 integer, id3 bigint, id4 integer, id5 bigint, id6 real, id7 double precision, id8 char(5), id9 char(10), id10 varchar(5), id11 varchar(10));

psql=# CREATE FUNCTION inc_char_fnc() RETURNS SETOF test_type AS $$
    VALUES (11, 12, 13, 14, 15, 1.1, 1.2, 'test1', 'test2', 'test3', 'test4')
    ;
$$ LANGUAGE SQL;
```

```
2. Create control files
# cat inc_char.ctl
WRITER = BINARY
PARSE_ERRORS = -1
OUT_COL = SMALLINT
OUT_COL = INTEGER
OUT_COL = BIGINT
OUT_COL = UNSIGNED SMALLINT
OUT_COL = UNSIGNED INTEGER
OUT_COL = FLOAT
OUT_COL = DOUBLE
OUT_COL = CHAR (5)
OUT_COL = CHAR (10)
OUT_COL = VARCHAR (5)
OUT_COL = VARCHAR (10)
MULTI_PROCESS = YES
```

```
3. Run to pg_bulkload and it seems to work.
bin/pg_bulkload inc_char.ctl -i "inc_char_fnc()" -o TYPE=FUNCTION -O inc_char_test.out

NOTICE: BULK LOAD START
NOTICE: BULK LOAD END
        0 Rows skipped.
        1 Rows successfully loaded.
        0 Rows not loaded due to parse errors.
        0 Rows not loaded due to duplicate errors.
        0 Rows replaced with new rows.
```

```
4. Make sure that we can load the binary data to a table
psql=# CREATE TABLE test (id1 smallint, id2 integer, id3 bigint, id4 integer, id5 bigint, id6 real, id7 double precision, id8 char(5), id9 char(10), id10 varchar(5), id11 varchar(10));

# diff  inc_char_test.out.ctl.bk inc_char_test.out.ctl        main [19aca49b] modified untracked
2c2,3
< OUTPUT = inc_char_test
---
> #OUTPUT = inc_char_test
> TABLE = test

# bin/pg_bulkload inc_char_test.out.ctl 

psql=# SELECT * FROM test;
id1 | id2 | id3 | id4 | id5 | id6 | id7 |  id8  |    id9     | id10  |    id11
-----+-----+-----+-----+-----+-----+-----+-------+------------+-------+------------
  11 |  12 |  13 |  14 |  15 | 1.1 | 1.2 | test1 | test2      | test3 | test4
(1 row)
```

The above procedure works for this case. So, at least, I think we need to add the pg_bulkload's document to note this behavior.

Although I also think to change the expected type from cstring to char/varchar, I didn't have any idea to handle them yet. I wonder that to add documents is enough because pg_bulkload checks the type again itself.

If the direction to modify the document is ok, I'll make the patch.

Regards,

**Comment by MoonInsung** [comment] 2021-04-23 04:50
Dear mikecaat.

Thank you for sharing the solution.

Wow... that's a very excellent opinion.
I have tried to modify the internal operation of pg_bulkload about the improved executor of the PG13 function so far. However, as your opinion suggests, this can very easily solve a new way to use pg_bulkload.
I haven't considered these solutions at all.

Although, in the case of using any shell in any environment, there may be inconvenient to modify the shell script. (like automation script)
But, I think this is inevitable because it is a response to the improvements made in PG13.

I agree with your opinion and would like to use this suggestion.
If you plan to write a PR, please modify the manual and regression test (PG13 or higher).

Once again, thank you for sharing such an excellent opinion.

Best regards.
Moon.

**Comment by mikecaat** [comment] 2021-04-23 04:58
Dear @mikecaat 

Thank for reviewing! OK, I'll make a PR later.

**Closed** 2021-04-30 06:13 UTC
