### ISSUE TITLE
PostgreSQL 14 support

### ISSUE THREAD

**Issue by devrimgunduz** [ossc-db/pg_bulkload#105] opened 2021-06-04 11:38 UTC
Hi,

v14 beta1 is out, and latest release cannot be built against v14. Can you please take a look?

Thanks! Devrim

> /usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I../include -I/usr/pgsql-14/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o pgut/pgut-list.bc pgut/pgut-list.c
pgut/pgut.c:394:2: warning: implicit declaration of function 'simple_prompt' is invalid in C99 [-Wimplicit-function-declaration]
        simple_prompt("Password: ", buf, sizeof(buf), false);
        ^
1 warning generated.
pgut/pgut.c: In function 'prompt_for_password':
pgut/pgut.c:394:9: warning: implicit declaration of function 'simple_prompt' [-Wimplicit-function-declaration]
  394 |         simple_prompt("Password: ", buf, sizeof(buf), false);
      |         ^~~~~~~~~~~~~
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection pg_bulkload.o recovery.o pgut/pgut.o pgut/pgut-fe.o pgut/pgut-list.o  -L/usr/pgsql-14/lib  -L/usr/lib64  -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-14/lib',--enable-new-dtags -Wl,--build-id  -L/usr/pgsql-14/lib -lpq -L/usr/pgsql-14/lib -lpgcommon -lpgport -lselinux -llz4 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lpthread -lrt -ldl -lm -o pg_bulkload
/usr/bin/ld: stringinfo.o (symbol from plugin): in function `initStringInfo':
(.text+0x0): multiple definition of `appendStringInfoVA'; pgut/pgut.o (symbol from plugin):(.text+0x0): first defined here
pgut/pgut.c:394:9: warning: type of 'simple_prompt' does not match original declaration [-Wlto-type-mismatch]
  394 |         simple_prompt("Password: ", buf, sizeof(buf), false);
      |         ^
../../../../../../../../../../../../../../../var/lib/pgsql/rpm14testing/BUILD/postgresql-14beta1/src/common/sprompt.c:38:1: note: return value type mismatch
../../../../../../../../../../../../../../../var/lib/pgsql/rpm14testing/BUILD/postgresql-14beta1/src/common/sprompt.c:38:1: note: 'simple_prompt' was previously declared here
../../../../../../../../../../../../../../../var/lib/pgsql/rpm14testing/BUILD/postgresql-14beta1/src/common/sprompt.c:38:1: note: code may be misoptimized unless '-fno-strict-aliasing' is used
../../../../../../../../../../../../../../../var/lib/pgsql/rpm14testing/BUILD/postgresql-14beta1/src/common/stringinfo.c:133:1: warning: type of 'appendStringInfoVA' does not match original declaration [-Wlto-type-mismatch]
pgut/pgut.c:1212:1: note: return value type mismatch
 1212 | appendStringInfoVA(StringInfo str, const char *fmt, va_list args)
      | ^
pgut/pgut.c:1212:1: note: type '_Bool' should match type 'int'
pgut/pgut.c:1212:1: note: 'appendStringInfoVA' was previously declared here
pgut/pgut.c:1212:1: note: code may be misoptimized unless '-fno-strict-aliasing' is used
collect2: error: ld returned 1 exit status
make[2]: *** [/usr/pgsql-14/lib/pgxs/src/makefiles/pgxs.mk:462: pg_bulkload] Error 1
make[2]: Leaving directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_bulkload/master/pg_bulkload-VERSION3_1_18/bin'
make[1]: *** [Makefile:27: all] Error 2
make[1]: Leaving directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_bulkload/master/pg_bulkload-VERSION3_1_18'
error: Bad exit status from /var/tmp/rpm-tmp.gHRpgV (%build)

**Comment by mikecaat** [comment] 2021-06-04 12:10
Hi,

Thanks!
Now, we are working on #104.

If you can, please check it.
Please feel free to comment.

Regards,

**Comment by devrimgunduz** [comment] 2021-06-07 13:10
Hi,

Thanks! With the patch I can build the package and also regression tests run fine.

When will you release a new version?

Regards, Devrim

**Comment by mikecaat** [comment] 2021-06-08 05:55
Hi,

Thanks for testing!

We will release a new version from September to December 
because PostgreSQL v14 final release will be done in late 2021. 

But, we'll continuously support for v14 beta and rc versions in master branch. 
For example, we'll merge them to the branch if reviews of #104 are done.

Regards, Masahiro

**Comment by devrimgunduz** [comment] 2021-09-20 13:59
Hi,

RC1 will be out this week. 14.0 is due next week.

Besides that, when you don't release *before* v14 rc1/final, upgrades will fail.

Any chance for a quick release this week?

Thanks! Devrim

**Comment by mikecaat** [comment] 2021-09-21 00:20
Hi, 

Thanks for reporting the fail.

We'll work for that. But, we don't have any plan to release the next version 
_before_ the v14 rc1/final version will be released because we'll test with fixed source code. Sorry.

Regards, Masahiro Ikeda

**Comment by devrimgunduz** [comment] 2021-09-21 19:49
Any updates? v14 is around the corner.

**Comment by mikecaat** [comment] 2021-09-21 23:32
I tested with rc1 (REL_14_RC1), and I found the all regression tests passed.
It seems not to need updating though I'll check the release notes just in case.

So, if you want to upgrade to rc1, you can use the master branch source code.

**Closed** 2023-01-05 08:16 UTC
Labels: enhancement
