### ISSUE TITLE
Can't  load columns with multilines value

### ISSUE THREAD

**Issue by dmitrypisanko** [ossc-db/pg_bulkload#36] opened 2017-01-03 01:12 UTC
Hi, i try to import csv ( ~100K rows) with some multiline columns. Allways recieve same error

NOTICE: BULK LOAD START
NOTICE: BULK LOAD END
	0 Rows skipped.
	0 Rows successfully loaded.
	1 Rows not loaded due to parse errors.
	0 Rows not loaded due to duplicate errors.
	0 Rows replaced with new rows.
WARNING: some rows were not loaded due to errors.

**Comment by amitlan** [comment] 2017-01-04 05:36
I am afraid pg_bulkload does not support parsing a single record spanning multiple lines.

Anyway, could you show a (possibly redacted) snippet of your input record text that is multi-line?

**Comment by dmitrypisanko** [comment] 2017-01-04 12:22
Example of instagram media with multiline description

`1419637835020297588,1139629962,2017-01-03` 17:33:59+03,BOzkRbiFuV0,0,0,19,3050,"THE ROLLING STONES//
streets of love
#sevilla `#home",https://scontent.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/c0.134.1080.1080/15538925_1706067763039671_146135592231501824_n.jpg?ig_cache_key=MTQxOTYzNzgzNTAyMDI5NzU4OA%3D%3D.2.c,https://scontent.cdninstagram.com/t51.2885-15/sh0.08/e35/c0.134.1080.1080/15538925_1706067763039671_146135592231501824_n.jpg?ig_cache_key=MTQxOTYzNzgzNTAyMDI5NzU4OA%3D%3D.2.c,f,"{sevilla,home}",{},0,0`

Field look like "THE ROLLING STONES//
streets of love
#sevilla `#home"

**Comment by bwtakacy** [comment] 2017-01-04 13:42
Hmm.
In current implementation, pg_bulkload does not allow the multiline field.

https://github.com/ossc-db/pg_bulkload/blob/VERSION3_1_STABLE/lib/parser_csv.c#L573-L589
```
			/*
			 * Finding a newline here means that we've got a unterminated
			 * quoted field; break to error out before we run out of buffer
			 * space!  Considering that we may come back if we don't exceed
			 * maximum allowed parse errors, set up self->next to point to
			 * the next line's 1st field.
			 */
			else if (c == '\n')
			{
				self->next = self->rec_buf + i + 1;
				if (self->rec_buf[i - 1] == '\n')
					i--;
				if (self->rec_buf[i - 1] == '\r')
					i--;
				self->rec_buf[i] = '\0';
				break;
			}
```
With comment out these codes, I can insert multiline value without parse error.

```
$ cat /tmp/foo.csv 
1,foo
2,bar
3,"THE ROLLING STONES//
streets of love 
#sevilla #home"
$ cat doc/sample_csv.ctl 
#
# sample_csv.ctl -- Control file to load CSV input data
#
#    Copyright (c) 2007-2016, NIPPON TELEGRAPH AND TELEPHONE CORPORATION
#
OUTPUT = foo                   # [<schema_name>.]table_name
INPUT = /tmp/foo.csv  # Input data location (absolute path)
TYPE = CSV                            # Input file type
QUOTE = "\""                          # Quoting character
ESCAPE = \                            # Escape character for Quoting
DELIMITER = ","                       # Delimiter
$ pg_bulkload doc/sample_csv.ctl 
NOTICE: BULK LOAD START
NOTICE: BULK LOAD END
	0 Rows skipped.
	3 Rows successfully loaded.
	0 Rows not loaded due to parse errors.
	0 Rows not loaded due to duplicate errors.
	0 Rows replaced with new rows.
[postgres@localhost pg_bulkload]$ psql
psql (10devel)
Type "help" for help.

[local] 26618 postgres=# SELECT * FROM foo;
 a |          b           
---+----------------------
 1 | foo
 2 | bar
 3 | THE ROLLING STONES//+
   | streets of love     +
   | #sevilla #home
(3 rows)

```

This change does not break the regression tests but I have not confirmed it is safe...

**Comment by amitlan** [comment] 2017-01-05 05:09
Oops, that code is part of the the bug fix I proposed in PR #30 that was merged.

Basically, if we do not look for a newline here, the loop would *indefinitely* keep expanding the buffer until a terminating quote is found, which in the worst case, would be never (most likely due to an unclean input file, which is the case that PR was meant for).

But I think the bug fix actually broke a feature serving valid use case such as this one.  I will look into that.  PostgreSQL's COPY FROM CSV code sounds like a good place to start (unsurprisingly, COPY FROM CSV handles both quoted multi-line fields and also handles the error scenario gracefully).

**Comment by bwtakacy** [comment] 2017-01-05 13:33
@amitlan 
Wow. 
I did not notice about this regression in that PR review...

@dmitrypisanko 
This is not a safety fix so please use as a temporal workaround:)

**Comment by dmitrypisanko** [comment] 2017-01-05 13:52
@bwtakacy i understand. I am export data by using COPY TO CSV, so i hope where are no problem with data )

**Comment by amitlan** [comment] 2017-01-18 05:46
By the way, I have reverted the commit that caused this feature to stop working.  You can see that this issue is now fixed by installing pg_bulkload with the latest commit in the master branch.

So, marking this issue as closed.

**Closed by amitlan** 2017-01-18 05:46 UTC
